import Vue from 'vue'

import './styles/quasar.styl'
import 'quasar/dist/quasar.ie.polyfills'
import lang from 'quasar/lang/zh-hans.js'
import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/material-icons/material-icons.css'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
import '@quasar/extras/ionicons-v4/ionicons-v4.css'
import '@quasar/extras/mdi-v3/mdi-v3.css'
import '@quasar/extras/eva-icons/eva-icons.css'
import {
  Notify,
  Dialog,
  Loading,
  AppFullscreen,
  LocalStorage,
  SessionStorage,
  Cookies,
  ClosePopup,
  Quasar,
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QInput,
  QField,
  QPageSticky,
  QAvatar,
  QScrollArea,
  QTable,
  QTh,
  QTr,
  QTd,
  QImg,
  QParallax,
  QTabs,
  QTab,
  QRouteTab,
  QSplitter,
  QTabPanels,
  QTabPanel,
  QPopupEdit,
  QDialog,
  QTooltip,
  QBar,
  QCard,
  QSpace,
  QCardSection,
  QCheckbox,
  QLinearProgress,
  QSeparator,
  QCardActions,
  QSelect,
  QBadge,
  QVideo,
  QToggle
} from 'quasar'

Vue.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QInput,
    QField,
    QPageSticky,
    QAvatar,
    QScrollArea,
    QTable,
    QTh,
    QTr,
    QTd,
    QImg,
    QParallax,
    QTabs,
    QTab,
    QRouteTab,
    QSplitter,
    QTabPanels,
    QTabPanel,
    QPopupEdit,
    QDialog,
    QTooltip,
    QBar,
    QCard,
    QSpace,
    QCardSection,
    QCheckbox,
    QLinearProgress,
    QSeparator,
    QCardActions,
    QSelect,
    QBadge,
    QVideo,
    QToggle,
    ClosePopup,
    Notify,
    Dialog,
    Loading,
    AppFullscreen,
    LocalStorage,
    SessionStorage,
    Cookies
  },
  directives: {
    ClosePopup
  },
  plugins: {
    Notify,
    Dialog,
    Loading,
    AppFullscreen,
    LocalStorage,
    SessionStorage,
    Cookies
  },
  lang: lang
})
